[shadowsocks]
server = "example.com"
server_port = "8080"
password = "some-password"
method = "aes-256-cfb"

[negar]
api-key = "API_KEY"
api-secret = "SECRET_KEY"

[chatterbox]
api-key = "API_KEY"
api-secret = "SECRET_KEY"
