[shadowsocks]
server = "example.com"
server_port = "8080"
password = "some-password"
method = "aes-256-cfb"

[s3cmd]
host_base = "example.com"
host_bucket= "bucket"
access_key = "ACCESS_TOKEN"
secret_key = "SECRET_KEY"

[negar]
api-key = "API_KEY"
api-secret = "SECRET_KEY"

[chatterbox]
api-key = "API_KEY"
api-secret = "SECRET_KEY"
